language: swift
osx_image: xcode9.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDKPFS.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDKPFS iOS"
    - IOS_TEST_SCHEME="TestApp"
    - IOS_SDK=iphonesimulator11.0
    - FRAMEWORK_NAME=VirgilSDKPFS
  matrix:
    - DESTINATION="OS=11.0,name=iPhone SE"   SCHEME="$IOS_FRAMEWORK_SCHEME"    TEST_SCHEME="$IOS_TEST_SCHEME"    SDK="$IOS_SDK"    CARTHAGE_PLATFORM_NAME="iOS"  RUN_TESTS="YES"  PUBLISH_CARTHAGE="YES"

before_install:
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - carthage bootstrap --no-use-binaries --platform "$CARTHAGE_PLATFORM_NAME";
  # Build Framework
  - xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -verbose -project "$PROJECT" -scheme "$TEST_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build test | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current --platform "$CARTHAGE_PLATFORM_NAME";
    fi

before_deploy:
  # Generate carthage framework
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage archive $FRAMEWORK_NAME;
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: Rj0sYXg1pmr0DY9DfdPVjX/kK9hhF4/iOAbZi0R6i9+nzZoP5Ouy3QP8Cd6WWz5UcnB36H8Hk98FVmEQrZx3qCx8bYtj2DrEC6/fKtnYMCym/BXwEHuVFSXBb7edvk1dH+7cjO770puZt8cqwygzEeobB+nr8wW+ZufdRLIHE92I1wwOxJCI4Ow0gbmif2+galYLu4iYHDivtyIsHTXNHZ6s9HjuhWCo8PVOKWofu1AnnzsrSKsZzZ9PaeLdkMSuJMJkci2UCRu0t6CAZ6vyXKe+m7S2WnqirTz3ryVBwxvhjP6cSiMx/qs3Kjz5l06oO0DKokdUmDGCibHejDRjoC9NMsZ+c49ZpzGnN9/UcjTr1kwshrGqvWNIgpwNTJP44mjvy4Ws+CxhvAPCuxREI6SzagL3bTzdkZ5NVzQKv3FclOz3fBJLYEo529/xqgr2O3JnNQfevV3HLdMo7rLWSV7Yce4JiyPG4Bur3kh6iZXUUq85aP6KfH8+7d582S3x9zarBnRuOo265p5pdeC+84/fNfjtzMgkOjDIUYennlyV2vj61Gket3FC2VuHRi7CWNcF7yu0pbdUhsLjQX7O04RwTnrwe9AheZkkNualbN2fxfr01zmyuwT4I4nLgKM+RYrHTkifGMaLeG3ghTkB0m8J+G46nYFP6pRVU137jJE=
    file: "$FRAMEWORK_NAME.framework.zip"
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-sdk-pfs-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"
      